version: "3.9"
services:
  nginx:
    image: nginx:1.25.0
    container_name: vendee-example-web-nginx
    restart: always
    networks:
      traefik:
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${STATIC_PATH}:/www/data:ro
      - nginx:/var/log/nginx
    labels:
      - traefik.enable=true

      - traefik.http.routers.nginxVendeeExampleWeb.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxVendeeExampleWeb.service=nginxVendeeExampleWeb
      - traefik.http.routers.nginxVendeeExampleWeb.entryPoints=http

      - traefik.http.routers.nginxVendeeExampleWebHttps.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.nginxVendeeExampleWebHttps.service=nginxVendeeExampleWeb
      - traefik.http.routers.nginxVendeeExampleWebHttps.entryPoints=https
      - traefik.http.routers.nginxVendeeExampleWebHttps.tls.certResolver=letsEncrypt

      - traefik.http.services.nginxVendeeExampleWeb.loadbalancer.server.port=80

networks:
  traefik:
    external: true
    name: traefik

volumes:
  nginx: